"""Inject build timestamp into src/build_info.h before each compile."""
import os
from datetime import datetime

Import("env")

INFO = os.path.join(env["PROJECT_DIR"], "src", "build_info.h")
TS = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
VER = env.GetProjectOption("custom_version", "0.1.0")

contents = (
    "// Auto-generated by scripts/pre_build.py - do not edit by hand.\n"
    "#pragma once\n\n"
    '#define FR3K_VERSION "{ver}"\n'
    '#define FR3K_NAME    "fR3k"\n'
    '#define FR3K_BUILD   "{ts}"\n'
    '// Compatibility aliases for unchanged internal modules.\n'
    '#define ON3PORK_VERSION FR3K_VERSION\n'
    '#define ON3PORK_NAME    FR3K_NAME\n'
    '#define ON3PORK_BUILD   FR3K_BUILD\n'
).format(ver=VER, ts=TS)

with open(INFO, "w", encoding="ascii") as f:
    f.write(contents)

print("[pre_build] wrote {p} (v={v} build={t})".format(p=INFO, v=VER, t=TS))
