// fR3k v3 Australian IR power-code DB.
// AUTO-GENERATED by tools/aus_ir_codes.py - do not edit by hand.
// Re-run `python3 tools/aus_ir_codes.py` after editing
// tools/aus_ir_codes.yaml.
//
// Carrier: 38 kHz, 940 nm, single-shot only. No repeats. No
// long-burst mode. Every frame is one user action.
#pragma once

#include <stdint.h>
#include <stddef.h>

namespace AuBrand {

enum Proto : uint8_t {
    AUS_PROTO_NEC = 0,
    AUS_PROTO_NEC42 = 1,
    AUS_PROTO_SAMSUNG = 2,
    AUS_PROTO_SONY = 3,
};

struct Brand {
    Proto proto;
    uint16_t addr;
    uint16_t cmd;
    uint8_t bits;   // SONY only
    char brand[16];
    char model[16];
    char note[24];
};

constexpr size_t kBrandCount = 75;
constexpr uint8_t kCarrierKHz = 38;
constexpr uint8_t kWavelengthNm = 940;
constexpr bool kSingleShot = true;

constexpr Brand kBrands[kBrandCount] = {
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x01, (uint8_t)12, "Hisense", "AU6100U", "Power on/off" },
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x02, (uint8_t)12, "Hisense", "AU6100U", "Vol+" },
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x03, (uint8_t)12, "Hisense", "AU6100U", "Vol-" },
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x0C, (uint8_t)12, "Hisense", "AU6100U", "Input" },
    { AUS_PROTO_NEC42, (uint16_t)0x04, (uint16_t)0x08, (uint8_t)12, "LG", "AU_LM5500", "Power" },
    { AUS_PROTO_NEC42, (uint16_t)0x04, (uint16_t)0x0B, (uint8_t)12, "LG", "AU_LM5500", "Input HDMI1" },
    { AUS_PROTO_NEC42, (uint16_t)0x04, (uint16_t)0x44, (uint8_t)12, "LG", "AU_LM5500", "Mute" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x02, (uint8_t)12, "Samsung", "UA55KU7000", "Power" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x03, (uint8_t)12, "Samsung", "UA55KU7000", "Vol+" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x04, (uint8_t)12, "Samsung", "UA55KU7000", "Vol-" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x0C, (uint8_t)12, "Samsung", "UA55KU7000", "Source" },
    { AUS_PROTO_NEC, (uint16_t)0xAA, (uint16_t)0x0F, (uint8_t)12, "Sharp", "LC-50LE860", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0xAA, (uint16_t)0x12, (uint8_t)12, "Sharp", "LC-50LE860", "Channel+" },
    { AUS_PROTO_SONY, (uint16_t)0, (uint16_t)0xA90, (uint8_t)12, "Sony", "KDL32W650A", "Power" },
    { AUS_PROTO_SONY, (uint16_t)0, (uint16_t)0x540, (uint8_t)12, "Sony", "KDL32W650A", "Vol+" },
    { AUS_PROTO_NEC, (uint16_t)0x32, (uint16_t)0x0A, (uint8_t)12, "Foxtel", "IQ4", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x32, (uint16_t)0x18, (uint8_t)12, "Foxtel", "IQ4", "Channel+" },
    { AUS_PROTO_NEC, (uint16_t)0x32, (uint16_t)0x19, (uint8_t)12, "Foxtel", "IQ4", "Channel-" },
    { AUS_PROTO_NEC, (uint16_t)0x40, (uint16_t)0x01, (uint8_t)12, "Telstra", "T-Box", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x40, (uint16_t)0x4B, (uint8_t)12, "Telstra", "T-Box", "Menu" },
    { AUS_PROTO_NEC42, (uint16_t)0x21, (uint16_t)0x01, (uint8_t)12, "Optus", "Fetch", "Power" },
    { AUS_PROTO_NEC42, (uint16_t)0x21, (uint16_t)0x05, (uint8_t)12, "Optus", "Fetch", "Record" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x10, (uint8_t)12, "Mitsubishi", "MSZ-GL50", "AC power" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x11, (uint8_t)12, "Mitsubishi", "MSZ-GL50", "AC +1C" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x12, (uint8_t)12, "Mitsubishi", "MSZ-GL50", "AC -1C" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x13, (uint8_t)12, "Mitsubishi", "MSZ-GL50", "AC fan" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x01, (uint8_t)12, "Daikin", "FTXM", "Power on" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x02, (uint8_t)12, "Daikin", "FTXM", "Power off" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x06, (uint8_t)12, "Daikin", "FTXM", "Mode cool" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x07, (uint8_t)12, "Daikin", "FTXM", "Mode heat" },
    { AUS_PROTO_NEC, (uint16_t)0x3E, (uint16_t)0x01, (uint8_t)12, "Panasonic", "CS-Z50ZKR", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x3E, (uint16_t)0x03, (uint8_t)12, "Panasonic", "CS-Z50ZKR", "Cool" },
    { AUS_PROTO_NEC, (uint16_t)0x3E, (uint16_t)0x04, (uint8_t)12, "Panasonic", "CS-Z50ZKR", "Heat" },
    { AUS_PROTO_NEC, (uint16_t)0x44, (uint16_t)0x01, (uint8_t)12, "Kelvinator", "KSD25", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x44, (uint16_t)0x09, (uint8_t)12, "Kelvinator", "KSD25", "Fan high" },
    { AUS_PROTO_NEC, (uint16_t)0x55, (uint16_t)0x01, (uint8_t)12, "Carrier", "42S", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x55, (uint16_t)0x07, (uint8_t)12, "Carrier", "42S", "Cool" },
    { AUS_PROTO_NEC, (uint16_t)0x60, (uint16_t)0x01, (uint8_t)12, "Bonaire", "BonA", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x60, (uint16_t)0x09, (uint8_t)12, "Bonaire", "BonA", "Cool" },
    { AUS_PROTO_NEC, (uint16_t)0x80, (uint16_t)0x01, (uint8_t)12, "Hunter", "Pacific", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x80, (uint16_t)0x02, (uint8_t)12, "Hunter", "Pacific", "Speed low" },
    { AUS_PROTO_NEC, (uint16_t)0x80, (uint16_t)0x03, (uint8_t)12, "Hunter", "Pacific", "Speed high" },
    { AUS_PROTO_NEC, (uint16_t)0x88, (uint16_t)0x01, (uint8_t)12, "Mercator", "AC226", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x88, (uint16_t)0x09, (uint8_t)12, "Mercator", "AC226", "Light" },
    { AUS_PROTO_NEC, (uint16_t)0x90, (uint16_t)0x01, (uint8_t)12, "Eglo", "FanAir", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x90, (uint16_t)0x06, (uint8_t)12, "Eglo", "FanAir", "Speed 2" },
    { AUS_PROTO_NEC, (uint16_t)0x95, (uint16_t)0x01, (uint8_t)12, "Beacon", "Ceil1", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x95, (uint16_t)0x04, (uint8_t)12, "Beacon", "Ceil1", "Light" },
    { AUS_PROTO_NEC, (uint16_t)0x99, (uint16_t)0x01, (uint8_t)12, "Brilliant", "Tempo", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x99, (uint16_t)0x06, (uint8_t)12, "Brilliant", "Tempo", "Speed 2" },
    { AUS_PROTO_NEC, (uint16_t)0xA0, (uint16_t)0x01, (uint8_t)12, "Dimplex", "RFi", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0xA0, (uint16_t)0x07, (uint8_t)12, "Dimplex", "RFi", "Boost" },
    { AUS_PROTO_NEC, (uint16_t)0xA5, (uint16_t)0x01, (uint8_t)12, "Bromic", "Platinum", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0xA5, (uint16_t)0x09, (uint8_t)12, "Bromic", "Platinum", "High" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x04, (uint16_t)0x01, (uint8_t)12, "Panasonic", "TH-43", "TV power" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x04, (uint16_t)0x03, (uint8_t)12, "Panasonic", "TH-43", "Vol+" },
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x20, (uint8_t)12, "Hisense", "AU3150", "Smart" },
    { AUS_PROTO_NEC, (uint16_t)0x10, (uint16_t)0x21, (uint8_t)12, "Hisense", "AU3150", "Menu" },
    { AUS_PROTO_NEC42, (uint16_t)0x04, (uint16_t)0x40, (uint8_t)12, "LG", "AU_LM6200", "Mute" },
    { AUS_PROTO_NEC42, (uint16_t)0x04, (uint16_t)0x60, (uint8_t)12, "LG", "AU_LM6200", "Aspect" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x0B, (uint8_t)12, "Samsung", "UA40K5000", "HDMI1" },
    { AUS_PROTO_SAMSUNG, (uint16_t)0x07, (uint16_t)0x0C, (uint8_t)12, "Samsung", "UA40K5000", "HDMI2" },
    { AUS_PROTO_NEC, (uint16_t)0xAA, (uint16_t)0x40, (uint8_t)12, "Sharp", "LC-32LE155", "Tools" },
    { AUS_PROTO_NEC, (uint16_t)0xAA, (uint16_t)0x41, (uint8_t)12, "Sharp", "LC-32LE155", "Teletext" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x20, (uint8_t)12, "Mitsubishi", "MSZ-AP25", "Mode dry" },
    { AUS_PROTO_NEC, (uint16_t)0x27, (uint16_t)0x21, (uint8_t)12, "Mitsubishi", "MSZ-AP25", "Mode fan" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x20, (uint8_t)12, "Daikin", "FTKC", "Fan auto" },
    { AUS_PROTO_NEC, (uint16_t)0x5A, (uint16_t)0x21, (uint8_t)12, "Daikin", "FTKC", "Fan low" },
    { AUS_PROTO_NEC, (uint16_t)0x3E, (uint16_t)0x10, (uint8_t)12, "Panasonic", "CS-RXZ", "Power auto" },
    { AUS_PROTO_NEC, (uint16_t)0x44, (uint16_t)0x10, (uint8_t)12, "Kelvinator", "KSD30", "Eco mode" },
    { AUS_PROTO_NEC, (uint16_t)0x80, (uint16_t)0x04, (uint8_t)12, "Hunter", "Pacific2", "Speed med" },
    { AUS_PROTO_NEC, (uint16_t)0x99, (uint16_t)0x09, (uint8_t)12, "Brilliant", "Tempo2", "Speed 3" },
    { AUS_PROTO_NEC, (uint16_t)0x88, (uint16_t)0x0C, (uint8_t)12, "Mercator", "AC228", "Light dim" },
    { AUS_PROTO_NEC, (uint16_t)0x30, (uint16_t)0x0A, (uint8_t)12, "Foxtel", "IQ3", "Power" },
    { AUS_PROTO_NEC, (uint16_t)0x30, (uint16_t)0x12, (uint8_t)12, "Foxtel", "IQ3", "Menu" },
};

}  // namespace AuBrand
